### ISSUE TITLE
Historic Data

### ISSUE THREAD

**Issue by bscully27** [vterron/fear-and-greed#10]
Is it possible to include historical data within the repo?
If not, where can I download the time series?

**Comment by Karlheinzniebuhr** [comment]
I'm interested in this too, I noticed it is possible to pull historic data from the api [https://api.alternative.me/fng/?limit=20](https://api.alternative.me/fng/?limit=20)

**Comment by vterron** [comment]
The library is just a wrapper for CNN's API and doesn't store any data, but #25 will add the functionality to look up the value for specific dates.
