### ISSUE TITLE
couldn't parse https://money.cnn.com/data/fear-and-greed/

### ISSUE THREAD

**Issue by HappyManWorld** [vterron/fear-and-greed#13]
Hello!
Two days ago has error: "couldn't parse https://money.cnn.com/data/fear-and-greed/"
I think, site was updated.

![image](https://user-images.githubusercontent.com/62791404/164990453-45ea933f-9605-46be-8bfb-28d0d2a64e47.png)

**Comment by vterron** [comment]
Thanks for the report! This was fixed in #12.
