### ISSUE TITLE
Endpoint returns HTTP response code 418 ("I'm a teapot")

### ISSUE THREAD

**Issue by weyCC81** [vterron/fear-and-greed#15]
**Current Output**
ValueError: couldn't parse https://money.cnn.com/data/fear-and-greed/

**Changes to Website**
https://edition.cnn.com/markets/fear-and-greed

**Comment by TheSnoozer** [comment]
Are you using the latest version?

**Comment by weyCC81** [comment]
I just upgraded from 0.1 to 0.2 but getting the same error, added the following lines to debug here "https://github.com/vterron/fear-and-greed/blob/master/src/fear_and_greed/cnn.py"
```
r.raise_for_status()  # raises exception when not a 2xx response
if r.status_code != 204:
    return r.json()
```

> HTTPError: 418 Client Error: Unknown Error for url: https://production.dataviz.cnn.io/index/fearandgreed/graphdata

Which is "Error 418 - I'm a teapot was an april ..."

**Comment by TheSnoozer** [comment]
Thanks indeed noticed this as well, should be fixed via https://github.com/vterron/fear-and-greed/pull/16

**Comment by weyCC81** [comment]
Thanks for your fast reply!

**Comment by vterron** [comment]
Release v0.3 with the fix is now [available on PyPI](https://pypi.org/project/fear-and-greed/0.3/).

Thanks @weyCC81 for the report and @TheSnoozer for contributing the fix.
