### ISSUE TITLE
Doesn't work after May 14

### ISSUE THREAD

**Issue by bbbirkan** [vterron/fear-and-greed#20]
File "/Users/xxxxx/lib/python3.8/site-packages/fear_and_greed/cnn.py", line xxx, in get
    raise ValueError("couldn't parse {}".format(URL))
ValueError: couldn't parse https://money.cnn.com/data/fear-and-greed/

**Comment by vterron** [comment]
Thanks for reporting this! #19 fixed this.

Release v0.4 with the fix is now [available on PyPI](https://pypi.org/project/fear-and-greed/0.4/).
